#!/bin/bash
echo "Hello Linux"
echo "Welcome to shell scripting begineer to advance project"

# modifying this flie:

echo "system information"
cat /etc/*release* | head -7
hostname
hostname -i
hostname -I
